# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    brochures_directory: '%kernel.project_dir%/public/uploads/brochures'
    moj_parametar: Moj Parametar Servis Tekst
   

services:
    # default configuration for services in *this* file
    
            
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%brochures_directory%'
            
    App\EventListener\BrochureUploaderListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            
    reddit_scraper:
        class: App\Service\RedditScraper
        public: true 
        arguments:
            - "@doctrine.orm.default_entity_manager"
            
    placeholder_service:
        class: App\Service\PlaceholderService
        public: true
        calls:
            - [ setLogger, [ "@logger" ] ]
        
        
    moj_servis:
        class: App\Service\MojServis
        public: true
        arguments:
            - '%moj_parametar%'
            - "@placeholder_service"
            
    
            
            
            

       
            

   